/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_shetj_audio_LameUtils */

#ifndef _Included_me_shetj_audio_LameUtils
#define _Included_me_shetj_audio_LameUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_shetj_audio_LameUtils
 * Method:    testInit
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_shetj_audio_LameUtils_testInit
  (JNIEnv *, jclass);

/*
 * Class:     me_shetj_audio_LameUtils
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_me_shetj_audio_LameUtils_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     me_shetj_audio_LameUtils
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_me_shetj_audio_LameUtils_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     me_shetj_audio_LameUtils
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_me_shetj_audio_LameUtils_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     me_shetj_audio_LameUtils
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_shetj_audio_LameUtils_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
